### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by jayvdb** [welbornprod/wp_site#1]
Hiya, please see https://github.com/EFForg/https-everywhere/issues/18867

**Comment by cjwelborn** [comment]
@jayvdb, wp_site is down. I'm working on something simpler. It will have its own repo, and this one will be archived. welbornprod.com currently points to cjwelborn.github.io, and I haven't properly set up HTTPS through GitHub. It's on my to-do list. Thanks for looking out though, and thanks for including my packages in the search. I suppose this issue would be better suited for [the new repo](https://github.com/cjwelborn/cjwelborn.github.io).

I'm closing it here, but feel free to open one over there. Just know that it is part of my plan to have my certificate and website in order.

Thanks again.

**Comment by cjwelborn** [comment]
@jayvdb, it looks like there are better tutorials for GoDaddy/GitHub-Pages nowadays. Last time I tried this I spent all night trying to get it to work, but this time it took like 15 minutes. I should be good now.  Thanks for reminding me.
